version: '3'
services:
  mtrc:
    environment:
      APP: mtrc
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "8087:8087"
    tty: true
  mongodb:
    image: "redis:latest"
