version: '3'
services:
  mtrc:
    restart: always
    environment:
      APP: mtrc
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8087:8087"
    tty: true
  mongodb:
    restart: always
    image: "mongodb:mongo:4.2.10-bionic"
