version: '3'
services:
  mtrc:
    restart: always
    environment:
      APP: mtrc
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "8087:8087"
    tty: true
  redis:
    restart: always
    image: "redis:latest"
